site_name: Tundra Tracker User Manual
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
  logo: assets/logo.svg
  palette:
    primary: teal
extra:
  alternate:
    # Switch to English
    - name: English
      link: <your-site>/en/
      lang: en

    # Switch to Japanese
    - name: 日本語
      link: <your-site>/jp/
      lang: jp

plugins:
  - search
  - print-site:
      add_to_navigation: true
      print_page_title: 'Print Site'
      add_print_site_banner: false
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      enabled: true
      exclude:
  
nav:
  - 'index.md'
  - Tracker:
    - Driver Installation: 'driver_installation.md'
    - Wireless Pairing: 'wireless_pairing.md'
    - Connecting with USB: 'connecting_by_usb.md'
    - Hardware Specifications: 'tracker_hardware.md'
    - Frequently Asked Questions: 'tracker_faq.md'
    - Complaince Information: 'tracker_compliance.md'
  - Dongle:
    - Quick Start: 'dongle_quickstart.md'
    - Hardware Specificaitons: 'dongle_hardware.md'
    - Frequently Asked Questions: 'dongle_faq.md'
    - Complaince Information: 'dongle_compliance.md'